name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tags
        id: vars
        run: |
          echo "sha_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker Image (sha + latest)
        run: |
          docker build -t mra00000/simple-novnc:${{ steps.vars.outputs.sha_tag }} .
          docker tag mra00000/simple-novnc:${{ steps.vars.outputs.sha_tag }} mra00000/simple-novnc:latest

      - name: Push Docker Images
        run: |
          docker push mra00000/simple-novnc:${{ steps.vars.outputs.sha_tag }}
          docker push mra00000/simple-novnc:latest

  docker-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image - Node
        run: |
          docker build -t mra00000/simple-novnc:node -f Dockerfile.node .
          docker tag mra00000/simple-novnc:node mra00000/simple-novnc:node

      - name: Push Docker Images - Node
        run: docker push mra00000/simple-novnc:node